-- La Maison de l'Ambre — catégories 1 à 46 sur 184
-- Généré pour la reprise de la base sur un autre projet Supabase.
-- Prérequis : avoir joué schema.sql, et s'être connecté une fois à l'app pour
-- que le compte existe dans auth.users.
-- Rejouable : les conflits mettent à jour, ils ne dupliquent pas.

insert into public.categories (
  project_id, url, name, external_id, parent_external_id, products_count,
  catalog_short_description, catalog_long_description,
  target_keyword, keyword_volume, keyword_difficulty, keyword_intent, keyword_data_at
) values
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/2-bijoux', 'Bijoux', 2, 1, 1192, 'Découvrez tous les bijoux et accessoires de LMDLA : nous proposons des bagues, colliers, pendentifs, chevalières, bracelets, boucles d''oreilles, en argent et argent doré, ornés de pierres naturelles. Nos collections de bijoux sont faites pour répondres à toutes vos attentes, alors profitez-en !', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/17-bijoux-argent', 'Bijoux en argent', 17, 2, 1063, 'Nos bijoux en argent incarnent la pureté et la force d’un métal intemporel. Poinçonnés, hypoallergéniques et livrés avec un certificat d’authenticité, ils reflètent un savoir-faire transmis par La Maison de l''Ambre depuis 1973. Colliers, bagues ou bracelets, découvrez nos créations en argent 925 poinçonnées, pensées pour accompagner et célébrer tous vos instants de vie.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/18-bijoux-dore', 'Bijoux doré', 18, 2, 58, 'Portez des bijoux dorés quand vous le souhaitez ! La Maison de l''Ambre vous dévoile une large collection de bijoux en argent 925 doré, qui vous permettent de rayonner sans dépasser votre budget. Faites-vous plaisir avec des créations tendances de qualité, qui capteront la lumière et tous les regards, pour longtemps.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/19-bijoux-femme', 'Bijoux pour femme', 19, 2, 1141, 'Les bijoux femme de LMDLA incarnent élégance et féminité. En argent 925 ou argent doré, ils subliment chaque tenue. Cadeau raffiné ou bijou de séduction, chaque création s’adapte aux styles du quotidien comme aux occasions spéciales, pour révéler la beauté de celles qui les portent.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/20-bijoux-homme', 'Bijoux pour homme', 20, 2, 7, 'Affirmez-vous avec des bijoux pour homme à la hauteur de vos attentes. Optez pour un style intemporel, à la fois discret et affirmé avec nos créations, associant qualité et design épuré. Serez-vous plutôt bracelet de perles sombres ou chevalière en argent ? LMDLA met la puissance des éléments au service de votre quotidien.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/21-bijoux-enfant', 'Bijoux pour enfant', 21, 2, 15, 'Vous cherchez des bijoux pour enfant combinant élégance, nature et sécurité ? La Maison de l''Ambre vous présente ses créations hypoallergéniques et inoxydables, spécialement pensées pour les plus petits. Baptême, anniversaire ou naissance, nos bijoux sont des souvenirs précieux, pour marquer chaque étape de leur vie avec douceur et originalité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/22-bagues', 'Bagues', 22, 2, 350, 'Les bagues sont un puissant symbole d''amour, d''élégance et de caractère ! Chez La Maison de l''Ambre, nous vous proposons des modèles de bagues simples ou originales, alliant savoir-faire artisanal et design intemporel. Argenté ou doré, anneau discret ou chevalière, nous avons certainement la bague que vous recherchez.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/23-bracelets', 'Bracelets', 23, 2, 145, 'Les bracelets sont des bijoux parfaits pour montrer son attachement ou pour se faire plaisir ! LMDLA est fière de vous présenter un large choix de bracelets de grande qualité, pensés dans nos ateliers parisiens pour mettre en valeur votre poignet et votre style. Nos bracelets vous permettent de combiner durabilité et raffinement.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/24-boucles-oreilles', 'Boucles d''oreilles', 24, 2, 267, 'Les boucles d''oreilles sont un symbole d''élégance, de liberté et de créativité. Elles font partie des bijoux que l''on peut changer au gré des envies et des tenues. LMDLA vous présente des paires de boucles d''oreilles pour tous les styles et toutes les tendances. Quelle que soit sa forme, trouvez celle qui vous permettra de briller au quotidien !', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/25-broches', 'Broches', 25, 2, 1, 'Vous aimez les accessoires élégants et originaux ? Optez pour les broches, qui apportent une touche singulière à chaque tenue. La Maison de l’Ambre propose des créations dorées ou argentées, idéales pour personnaliser vestes, manteaux ou foulards. Affirmez votre style avec justesse et raffinement, en toute simplicité avec nos broches légères.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/26-colliers', 'Colliers', 26, 2, 233, 'Les colliers LMDLA sont des bijoux délicats, associant élégance et intemporalité. Portés au quotidien ou pour de grandes occasions, ils sont les partenaires de tous les styles avec discrétion ou éclat, en fonction de vos choix ! Ras-du-cou, cascade, sautoir... Découvrez notre sélection variée de colliers, dessinés pour sublimer votre quotidien.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/27-chevalieres', 'Chevalières', 27, 2, 4, 'Symbole de transmission et d’identité, la chevalière est un bijou de tradition qui a su traverser le temps sans perdre de son prestige. Depuis plus d''un demi-siècle, La Maison de l’Ambre imagine des chevalières aux lignes épurées ou plus travaillées. Trouvez parmi notre catalogue celle qui reflétera à la fois votre puissance et votre énergie.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/28-chaines', 'Chaînes', 28, 2, 4, 'Sobres et élégantes, voici des chaînes à porter seules ou parées d''un joli pendentif, pour petits et grands. Quelle que soit la taille de leurs maillons, elles complèteront tous les styles avec raffinement. LMDLA vous présente des chaînes sélectionnées pour leur qualité et leur robustesse : une base essentielle, à offrir ou à porter chaque jour.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/29-pendentifs', 'Pendentifs', 29, 2, 167, 'Les pendentifs de La Maison de l’Ambre vous permettent de dévoiler votre personnalité ! Simples, discrets ou plus originaux, attirant tous les regards, notre sélection de pendentifs permet de contenter toutes les personnalités. Portés seuls, sur un cordon ou une chaîne, ils deviennent des bijoux uniques, parfaits pour sublimer un style ou marquer une occasion.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/30-bijoux-vintage', 'Bijoux vintage', 30, 2, 33, 'Découvrez nos bijoux vintage, évoquant le charme des époques passées. Chez La Maison de l''Ambre, nous nous sommes inspirés d''histoire et de différents styles rétro pour créer des pièces uniques. Portez-les pour affirmer votre personnalité singulière ou offrez-les comme cadeaux originaux, empreints d’authenticité et d’élégance intemporelle.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/31-bijoux-arbre-vie', 'Bijoux arbre de vie', 31, 2, 13, 'Symbole universel de croissance et d’harmonie, l’arbre de vie s’invite dans les créations LMDLA. Nous vous dévoilons des bijoux en métal précieux, délicats et porteurs de sens. Offerts en cadeau ou portés fièrement au quotidien, ils rappellent la force des liens qui nous unissent à la nature, à tout âge.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/32-bijoux-fleur-vie', 'Bijoux fleur de vie', 32, 2, 21, 'Découvrez les bijoux fleur de vie, ce motif sacré mis à l''honneur chez LMDLA. Cette fleur symbolique figure sur de nombreux bijoux de notre Maison, pour vous insuffler équilibre et harmonie. Laissez-vous séduire par cette forme géométrique intemporelle, idéale pour exprimer une connexion spirituelle ou pour faire un cadeau porteur de sens.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/33-bijoux-fantaisie', 'Bijoux fantaisie', 33, 2, 1117, 'Vous recherchez des bijoux fantaisie pour vitaminer vos tenues ou pour exprimer votre personnalité ? La Maison de l’Ambre est fière de suivre les tendances pour vous permettre d''apporter légèreté et originalité à votre style. Avec notre sélection de bijoux de qualité, mettez-vous en lumière tout en restant dans votre budget !', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/34-bijoux-pierres-naturelles', 'Bijoux en pierres naturelles', 34, 2, 1163, 'Découvrez nos bijoux en pierres naturelles, associant toujours qualité, élégance et puissance de la nature. Profitez des potentiels bienfaits de la lithothérapie tout en vous parant de bijoux uniques LMDLA. Soucieux de vous offrir le meilleur, nous contrôlons l''origine et la pureté de chaque pierre. Chaque bijou vous est livré avec son certificat d’authenticité.', 'Découvrez notre guide de présentation sur les bijoux en pierres naturelles et comment les choisir !

 Découvrez la beauté authentique de nos bijoux en pierres naturelles , symboles d’élégance et d’harmonie. Chaque pièce de notre collection de bijoux a été pensée pour révéler la puissance et la délicatesse de la nature, tout en soulignant votre style. Depuis 1973, notre bijouterie française s’inspire de l'' univers minéral pour façonner des bijoux uniques, à la fois raffinés et porteurs de sens.

 L''incroyable richesse des pierres naturelles

 Nos bijoux en pierre tirent leur singularité de la diversité des gemmes qui les composent. Chaque pierre gemme possède une teinte, une texture et une énergie potentielle qui lui sont propres. Ambre , Améthyste, quartz rose, aventurine, labradorite, turquoise, jade ou tourmaline : ces pierres (parfois semi-précieuses), aussi appelées pierres fines , reflètent notre savoir-faire ancestral et les valeurs qui nous tiennent à cœur. Chez La Maison de l''Ambre, nous avons un profond respect du matériau brut et des fruits de la nature en général !

 Nos artisans et partenaires sélectionnent avec soin chaque minéral selon sa couleur, sa qualité et son éclat. Les pierres sont ensuite taillées et polies pour mettre en valeur leur lumière naturelle et préserver ce petit truc en plus, qui les rend si précieux. Montées sur des bracelets, des colliers ou des boucles d''oreilles, dans nos ateliers installés à Paris et en Pologne, elles deviennent de précieux cadeaux qui mettent en valeur la personne qui les porte.

 Une grande variété de bijoux avec pierre

 Notre collection de bijoux en pierres naturelles se compose d’une grande variété de modèles, adaptés à tous les styles et toutes les envies. Parcourez les pages de nos différentes catégories pour trouver des bracelets élastiques ornés de perles d’améthyste ou de labradorite, des bagues serties de pierre gemme aux reflets changeants, des colliers délicats ou de longs et subtils sautoirs. Vous désirez mettre un peu de soleil dans vos tenues ? Découvrez nos différents modèles de boucles d’oreilles pendantes ou nos créoles plus discrètes, toujours ornées de nacre ou de pierres uniques.

 Parce que LMDLA souhaite ravir toutes les personnalités, hommes, femmes et enfants, nous réalisons des pièces en argent 925 ou en argent doré . Certains modèles de bracelets, de colliers ou de bagues associent plusieurs minéraux, de tailles égales ou différentes, pour un rendu coloré et énergisant ! Vous préférez la sobriété et l''élégance intemporelle ? Nous avons aussi les bijoux singuliers que vous recherchez !

 Entre raffinement et potentiels bienfaits

 Pour beaucoup, porter ou offrir un bijou en pierre naturelle permet d''associer esthétique et bien-être. En effet, selon les principes de la lithothérapie , chaque pierre serait associée à des vertus particulières. Cette discipline traditionnelle, non scientifique, attribue de potentiels bienfaits aux minéraux, et même si nous ne pouvons pas encore les prouver, ils se transmettent depuis des générations tout autour du globe. C''est bien ce qui explique que les bijoux en pierre sont convoités par ceux qui recherchent un lien plus profond avec la nature et qui sont attentifs à leur équilibre intérieur.

 L’améthyste, l'' aigue marine  et le lapis lazuli  sont par exemple liés à la sérénité, le quartz rose à l’amour et à la douceur tandis que la labradorite est un symbole de protection et de purification. De leurs côtés, la pierre oeil de tigre , la pierre de lune ou la tourmaline aideraient à se recentrer, avec des bénéfices particuliers pour le chakra du plexus solaire et le chakra racine. Offrir un bracelet orné de jade, d''agate, de nacre ou d''autres minéraux permet ainsi de combiner style, bien-être et raffinement.

 Porter des bracelets en pierres fines pourrait ainsi accompagner vos émotions et renforcer votre énergie au quotidien. Découvrez parmi notre vaste gamme les bijoux spirituels qui vous ressemblent, capables de mettre en valeur votre poignet, vos mains, votre visage ou votre port de tête, tout en vous faisant profiter de potentiels bienfaits quotidiennement.

 Des créations artisanales, durables et made in France

 Chez La Maison de l''Ambre, nous vous dévoilons des bijoux en pierres de qualité, réalisés à Paris et en Pologne, dans nos ateliers par des artisans passionnés ! Chaque création est composée de matériaux soigneusement sélectionnés pour leur qualité, leur authenticité et leur durabilité.

 Nous avons fait le choix, pour l''ensemble de nos gammes, de métaux hypoallergéniques, qui respectent les normes européennes et garantissent un confort parfait même pour les peaux sensibles. Nous privilégions une fabrication maîtrisée, avec un souci constant du détail : la forme de chaque pierre, sa teinte et la façon dont elle s''insère sur le bijou, sont pensées pour offrir une pièce harmonieuse et unique.

 Un bijou fantaisie orné d''une pierre fine apporte une touche d’éclat à vos tenues du quotidien, tandis que les modèles artisanaux plus travaillés deviennent de véritables talismans personnels.

 Comment choisir le bijou idéal ?

 Pour bien choisir votre bijou, laissez-vous guider par votre intuition et vos goûts. Vous pouvez opter pour une pierre liée à votre mois de naissance , à votre signe astrologique (on parle de bijou zodiaque ) ou simplement à sa  couleur et à ce qu’elle vous inspire. Vous êtes né un jour d''octobre ? Découvrez notre sélection de bagues ou bracelets ornés de tourmaline ou d''opale ! Notre site vous permet de chercher la pierre qui vous correspond, qu''elle figure parmi nos nouveautés ou notre sélection des meilleures ventes.

 Le bijou idéal chez LMDLA peut prendre de nombreuses formes : bagues , bracelets , colliers , pendentifs ou boucles d’oreilles . Certains préfèreront un bijou discret comme nos bagues en nacre blanches, d’autres une pièce imposante qui capte la lumière et attire tous les regards. Chaque achat est différent mais vous promet une qualité constante. Si vous cherchez un bijou spirituel avec de possibles propriétés, choisissez une pierre qui correspond à vos besoins du moment ou à ceux de la personne que vous souhaitez combler : calme, stress, confiance, bien-être ou amour.

 Entretien et soin des pierres naturelles

 Pour conserver la beauté et l’éclat de vos bijoux en pierres naturelles, il est conseillé de les nettoyer régulièrement à l’aide d’un chiffon doux et d’un peu d’eau claire. Évitez les produits chimiques mais également de laisser vos bijoux dans des pièces soumises à des variations de température trop brusques. La salle de bain n''est alors pas la meilleure pièce pour les ranger.

 Vous pouvez aussi, selon vos croyances, purifier vos pierres en les exposant à la lumière du soleil, de la lune, ou encore les recharger grâce à un amas de cristal de roche. Ces gestes simples raviveraient leur pouvoir énergétique, selon les principes de la lithothérapie que nous évoquions plus haut.

 Un cadeau porteur de sens

 Les bijoux en pierres naturelles font toujours plaisir à offrir. Pour un anniversaire, une fête, une naissance, une soirée hors du commun ou un simple geste d’affection, ils incarnent une attention pleine de douceur et de symbolique.

 Choisissez un bijou fantaisie en quartz rose, en aventurine, en grenat rouge ou en améthyste pour exprimer votre tendresse, tandis qu’un bracelet en œil de tigre ou en onyx noir évoquera la force et la sérénité.

 Offrir une pièce de notre collection de bijoux, c’est transmettre une part de la beauté de l''univers minéral, un lien entre la terre et la lumière.

 Découvrir, offrir ou porter un bijou en pierre naturelle LMDLA est parfait pour s''entourer de beauté et de symbolique. Nos bijoux en pierres naturelles, réalisés avec soin et passion, allient élégance et énergie positive. Laissez-vous séduire par la richesse du univers minéral et découvrez une collection de bijoux qui allie émotion, couleur et authenticité.

 Quels sont les bienfaits des pierres naturelles ?

 Les potentiels bienfaits des minéraux, appelés "propriétés", varient selon chaque pierre et sont détaillés dans les descriptions de nos produits et de nos catégories. Porter des pierres apporterait selon le type de résine ou de minéral, sérénité, protection, confiance en soi... Ces croyances relèvent de la lithothérapie et ne doivent jamais se substituer à un suivi médical.

 Comment entretenir ses bijoux en pierres naturelles ?

 Nettoyez-les avec douceur, évitez le contact prolongé avec l’eau ou les produits ménagers et rangez-les à l’abri de la lumière directe du soleil.

 Où acheter des bijoux en pierres naturelles ?

 Les créations La Maison de l''Ambre sont disponibles dans notre bijouterie en ligne , à des prix très attractifs. Vous trouverez sur les pages de notre site un large choix de bijoux en pierre naturelle et de bijoux fantaisie, tous conçus avec soin. L''origine de nos produits est rigoureusement contrôlée avant une expédition rapide et une livraison soignée.

 Quelles sont les pierres les plus populaires ?

 Parmi les pierres les plus appréciées, vous retrouverez chez LMDLA l''ambre, le quartz rose, l''aventurine, la labradorite, l’améthyste, la turquoise, le jade, la nacre blanche, le lapis lazuli, la tourmaline, la malachite ou encore l’œil de tigre.', null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/263-accessoires', 'Accessoires', 263, 2, 25, 'LMDLA vous propose des accessoires pour décorer vos pièces de vie. Pratiques, élégants et inspirés de la nature, ils reflètent le même souci du détail que l''ensemble de nos créations. Notre gamme d''accessoires de qualité rassemble des idées cadeaux originales, des objets du quotidien à l''image de nos bijoux : subtils et uniques.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/104-bagues-argent', 'Bagues en argent', 104, 17, 342, 'Classiques ou intemporelles, rétro ou ultra moderne, les bagues en argent La Maison de l’Ambre incarnent authenticité et pureté. Poinçonnées et certifiées, elles se déclinent en anneaux fins, bagues travaillées, ornées ou non de pierres colorées. Des créations en argent 925 durables et élégantes, pensées pour accompagner toutes les occasions avec simplicité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/105-bijoux-argent-femme', 'Bijoux en argent pour femme', 105, 17, 1057, 'Découvrez des bijoux en argent pour femme, pensés comme des éléments de séduction à part entière. Chez LMDLA, nous sommes persuadés que la féminité s’exprime aussi par la matière. Nos bijoux en argent 925, poinçonnés et certifiés, allient authenticité, qualité et élégance. Des pièces conçues pour accompagner la femme moderne, du quotidien aux grandes occasions.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/106-bijoux-argent-homme', 'Bijoux en argent pour homme', 106, 17, 4, 'Nos bijoux en argent pour homme associent authenticité, sobriété et dynamisme. Portés au quotidien, ils permettent d''affirmer un style intemporel, tout en soulignant force et virilité, à la manière de l''argent 925 choisi par LMDLA. Optez pour un savoir-faire maîtrisé avec nos créations, à arborer fièrement lors des petites et des grandes occasions.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/107-boucles-oreilles-argent', 'Boucles d''oreilles en argent', 107, 17, 246, 'Sages ou audacieuses, les boucles d’oreilles en argent traversent le temps sans perdre leur éclat. La Maison de l''Ambre vous dévoile des boucles en argent 925 poinçonnées et certifiées, s’adaptant à tous les styles. Bien plus qu''un accessoire, chaque paire vous permet d''affirmer votre personnalité, avec subtilité et audace !', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/108-bracelets-argent', 'Bracelets en argent', 108, 17, 122, 'Les bracelets en argent de La Maison de l’Ambre se placent au croisement de la sobriété et de la durabilité. Nous avons imaginé des bracelets en argent 925 qui se portent au quotidien et s’adaptent à toutes les tenues. Optez pour une création intemporelle associant éclat discret et élégance, envoyée avec son certificat d''authenticité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/109-colliers-argent', 'Colliers en argent', 109, 17, 189, 'Les colliers en argent sont des bijoux intemporels et lumineux, qui prouvent que la beauté n''a ni âge ni époque. La Maison de l’Ambre vous dévoile une large gamme de colliers en argent 925, livrés avec leur certificat d''authenticité. Ils complètent chaque style avec sobriété, subtilité et modernité, en fonction de votre personnalité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/110-pendentifs-argent', 'Pendentifs en argent', 110, 17, 161, 'Simple et efficace, c''est souvent ce que l''on dit des pendentifs en argent. Chez La Maison de l''Ambre, nous savons qu''ils sont encore plus que cela, incarnant authenticité et élégance. Poinçonnés en argent 925, nos pendentifs sont intemporels et durables ; des cadeaux judicieux pour accompagner toutes les étapes de votre vie.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/37-bagues-dore', 'Bagues doré', 37, 18, 8, 'Voici notre sélection de bagues dorées, conjuguant subtilement éclat et modernité ! Réalisées dans nos ateliers, en argent 925 doré, elles captent la lumière et subliment votre quotidien. Simples ou travaillées, larges ou très discrètes, nos créations sont des cadeaux accessibles qui allient brillance, qualité et raffinement, pour marquer les grandes étapes de vos vies.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/74-boucles-oreilles-dore', 'Boucles d''oreilles doré', 74, 18, 21, 'Les boucles d’oreilles dorées de LMDLA reflètent votre personnalité et vous invitent à vous mettre en lumière ! Réalisées en argent 925 doré, elles illuminent votre visage avec subtilité, tout en restant accessibles. Puces, anneaux ou modèles pendants, optez pour la paire qui vous permettra de suivre la mode, en combinant élégance et qualité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/84-bracelets-dore', 'Bracelets doré', 84, 18, 5, 'Bijou incontournable pour compléter une tenue avec justesse, les bracelets dorés de LMDLA allient modernité et brillance. Notre sélection de bracelets de qualité, en argent 925 doré, se portent seuls ou en accumulation, pour jouer avec les styles et les couleurs. Des bijoux tendances et élégants qui captent la lumière, tout en étant accessibles.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/92-colliers-dore', 'Colliers doré', 92, 18, 16, 'Jouez la carte de l''éclat et du raffinement avec l''un des colliers dorés LMDLA. Conçus en argent 925 doré, ce sont des bijoux accessibles et intemporels à porter au quotidien, pour ajouter lumière et modernité à chaque tenue. Jouez les superpositions ou optez pour un unique collier doré, pour traverser les saisons sans jamais se démoder.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/99-pendentifs-dore', 'Pendentifs doré', 99, 18, 6, 'Misez sur l''éclat et l''intemporalité avec nos pendentifs dorés. Notre sélection minutieuse de pendentifs en argent 925 doré, permet de personnaliser et même de sublimer tous les styles, de manière lumineuse et durable. Vous cherchez un cadeau discret et accessible ou un pendentif original attirant tous les regards ? Vous êtes bien chez LMDLA.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/114-bagues-femme', 'Bagues pour femme', 114, 19, 346, 'Découvrez les bagues pour femme LMDLA, des bijoux uniques qui subliment votre style au quotidien. Nos modèles se déclinent en anneaux fins et élégants ou en créations plus audacieuses et tendances, avec une qualité constante. Offrez une bague symbole d’amour et d’attachement ou choisissez un bijou de caractère pour affirmer fièrement votre personnalité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/115-bijoux-tendance-femme', 'Bijoux tendance pour femme', 115, 19, 322, 'Envie de suivre la mode sans renoncer à la qualité ? LMDLA propose des bijoux tendance pour femme originaux ou plus authentiques. Anneau discret ou parure éclatante, pendants d''oreilles ou bijou épinglé sur une veste, jouez avec les styles et exprimez votre personnalité grâce à des créations actuelles, tout en élégance.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/116-boucles-oreilles-femme', 'Boucles d''oreilles pour femme', 116, 19, 267, 'Les boucles d’oreilles pour femme sont l’accessoire incontournable qui sublime toutes les tenues. Créoles intemporelles, puces discrètes ou modèles plus originaux, LMDLA propose des créations capables de répondre à vos envies. Raffinées et élégantes, nos boucles d’oreilles se portent au quotidien comme lors de vos plus belles occasions, pour révéler toute votre féminité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/117-bracelets-femme', 'Bracelets pour femme', 117, 19, 138, 'Un bracelet est souvent plus qu’un bijou : c’est un lien, une promesse, un geste. La Maison de l’Ambre imagine des bracelets pour femmes uniques, féminins, délicats ou plus affirmés. Toutes nos créations raffinées sont conçues pour mettre en valeur tous les poignets, des cadeaux qui traversent les années, tout en gardant leur éclat.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/118-colliers-femme', 'Colliers pour femme', 118, 19, 222, 'Chaque collier pour femme signé LMDLA est une invitation à l’élégance. Chaîne fine, sautoir délicat ou création plus audacieuse, nos bijoux sont pensés pour sublimer le port de tête et révéler votre style. Offert en symbole précieux ou porté chaque matin, un collier féminin devient plus qu’un accessoire : c''est un subtil partenaire du quotidien.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/119-pendentifs-femme', 'Pendentifs pour femme', 119, 19, 167, 'Chaque pendentif pour femme est une courte histoire suspendue, un éclat discret qui accompagne votre quotidien. Les créations pour femme LMDLA prennent la forme de pendentifs variés, fins et délicats ou plus originaux, toujours très élégants. À offrir comme rappel de vos sentiments ou à porter chaque jour, ils signifient à la femme sa puissance !', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/120-bagues-homme', 'Bagues pour homme', 120, 20, 4, 'Les bagues pour homme sont des reflets subtils de leur personnalité ! Chez La Maison de l’Ambre, nous vous proposons plusieurs modèles de bagues de caractère, anneau épuré, bijou intemporel ou créations plus contemporaines. Elles deviennent des symboles de style et de personnalité, à porter chaque jour : serez-vous plutôt caractère affirmé ou sobriété discrète ?', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/121-bracelets-homme', 'Bracelets pour homme', 121, 20, 2, 'Sobres et résistants, nos bracelets pour homme vous aident à exprimer force et personnalité. Chaque pièce de La Maison de l''Ambre est conçue pour les hommes modernes, bien dans leurs baskets, pour un style discret ou affirmé. Découvrez nos bracelets intemporels, à porter au quotidien ou à offrir.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/122-colliers-homme', 'Colliers pour homme', 122, 20, 1, 'Les colliers pour homme de LMDLA conjuguent sobriété et caractère. Nous sommes fiers de vous présenter des bijoux intemporels, durables, correspondant exactement à vos besoins et à votre style. Découvrez le collier qui vous permettra d’affirmer votre personnalité avec élégance, qu’il s’agisse d’un choix personnel ou d’un cadeau minéral hors du commun.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/111-bijoux-bebe', 'Bijoux pour bébé', 111, 21, 15, 'Découvrez des bijoux pour bébé délicats, conçus pour célébrer les premiers instants de vie. Conformes aux normes européennes, ces créations marquent les naissances, baptêmes et anniversaires de vos proches de souvenirs précieux. Offerts avec tendresse, les bijoux pour bébé LMDLA deviennent des symboles uniques de protection et d’affection.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/112-bracelets-enfant', 'Bracelets pour enfant', 112, 21, 5, 'À la recherche du bracelet pour enfant idéal ? La Maison de l''Ambre vous présente sa collection de bracelets délicats et solides, pensés pour marquer les étapes de l’enfance. Naissance, baptême ou anniversaire, nos produits combinent douceur et sécurité. Parcourez nos différents modèles, simples et symboliques, des souvenirs précieux à garder toute une vie.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/113-colliers-enfant', 'Colliers pour enfant', 113, 21, 10, 'Nos colliers pour enfant marquent les étapes précieuses de la vie des tout-petits : naissance, baptême, anniversaire. Chez La Maison de l''Ambre, nous vous proposons des bijoux qui allient sécurité et délicatesse, pour longtemps. Offrez l''un de nos colliers comme un symbole de tendresse, souvenir qui marquera toute la famille.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/77-boucles-oreilles-dormeuses', 'Boucles d''oreilles dormeuses', 77, 24, 19, 'Pratiques et élégantes, les boucles d’oreilles dormeuses accompagnent vos journées en toute simplicité. Fermoir sécurisé, style raffiné, éclat discret : elles se portent à tous les âges, aussi bien seules qu''associées à d’autres parures de bijoux. Les dormeuses LMDLA sont conçues pour allier confort et charme, tout en soulignant la douceur d''un visage féminin.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/80-boucles-oreilles-pendantes', 'Boucles d''oreilles pendantes', 80, 24, 107, 'Légères et élégantes, nos boucles d’oreilles pendantes soulignent les traits de votre visage avec grâce. Simples ou plus travaillées, brillantes ou colorées, trouvez la paire de boucles La Maison de l''Ambre qui vous permettra de varier les styles et les plaisirs. Ensemble casual ou tenue de soirée, exprimez librement votre créativité.', null, null, null, null, null, null)
on conflict (project_id, url) do update set
  name = excluded.name, external_id = excluded.external_id,
  parent_external_id = excluded.parent_external_id,
  products_count = excluded.products_count,
  catalog_short_description = excluded.catalog_short_description,
  catalog_long_description = excluded.catalog_long_description,
  target_keyword = coalesce(excluded.target_keyword, public.categories.target_keyword),
  keyword_volume = coalesce(excluded.keyword_volume, public.categories.keyword_volume),
  keyword_difficulty = coalesce(excluded.keyword_difficulty, public.categories.keyword_difficulty),
  keyword_intent = coalesce(excluded.keyword_intent, public.categories.keyword_intent),
  keyword_data_at = coalesce(excluded.keyword_data_at, public.categories.keyword_data_at),
  updated_at = now();
