-- La Maison de l'Ambre — catégories 47 à 92 sur 184
-- Généré pour la reprise de la base sur un autre projet Supabase.
-- Prérequis : avoir joué schema.sql, et s'être connecté une fois à l'app pour
-- que le compte existe dans auth.users.
-- Rejouable : les conflits mettent à jour, ils ne dupliquent pas.

insert into public.categories (
  project_id, url, name, external_id, parent_external_id, products_count,
  catalog_short_description, catalog_long_description,
  target_keyword, keyword_volume, keyword_difficulty, keyword_intent, keyword_data_at
) values
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/44-bagues-vintage', 'Bagues vintage', 44, 30, 15, 'Les bagues vintage de La Maison de l’Ambre vous rappellent l’élégance des styles d’autrefois. Retrouvez nos bagues rétro, durables et originales, capables de vous transporter dans le temps. À offrir ou à porter pour se faire plaisir, elles sont des bijoux intemporels qui traversent les époques, parfaits pour affirmer votre personnalité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/82-boucles-oreilles-vintage', 'Boucles d''oreilles vintage', 82, 30, 9, 'Faites un retour en arrière audacieux avec les boucles d’oreilles vintage de La Maison de l’Ambre. Laissez-vous tenter par ces bijoux de caractère, mariant style rétro et brillance intemporelle. Choisissez parmi nos créations la parure qui vous rappellera le charme d’antan, tout en vous permettant d''affirmer votre personnalité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/103-pendentifs-vintage', 'Pendentifs vintage', 103, 30, 6, 'Un pendentif vintage raconte toujours une histoire, surtout choisi par les équipes de La Maison de l''Ambre. Inspirées des styles rétro, ces créations séduisent par leur caractère unique et par les souvenirs qu''ils évoquent. À offrir en cadeau original ou à porter comme un signe distinctif, pour une touche d''intemporel dans nos quotidiens animés.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/79-boucles-oreilles-fleur-vie', 'Boucles d''oreilles fleur de vie', 79, 32, 6, 'Parées d''un symbole d’harmonie, les boucles d’oreilles fleur de vie de LMDLA conjuguent géométrie sacrée et élégance. Choisissez la forme qui vous convient et laissez ce clin d''œil naturel sublimer vos tenues du quotidien. Nos boucles d''oreilles fleur de vie sont des cadeaux inspirants et des bijoux raffinés associant style et spiritualité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/88-bracelets-fleur-vie', 'Bracelets fleur de vie', 88, 32, 6, 'Symboles d’équilibre et d’énergie, les bracelets fleur de vie de La Maison de l’ambre sont bien plus que des bijoux. Ils se parent aussi d''une symbolique spirituelle particulière, comme une ode à la nature. Trouvez l''élégant bracelet qui ravira votre proche ou celle qu''il vous fera plaisir de porter chaque jour.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/101-pendentifs-fleur-vie', 'Pendentifs fleur de vie', 101, 32, 9, 'Les pendentifs fleurs de vie vous permettent de porter ce symbole d’harmonie et de vitalité au plus près de votre cœur. La Maison de l''Ambre a choisi des pendentifs de qualité, en métal précieux, pour les amateurs d''élégance et de nature. Offrez un bijou porteur de sens, comme un talisman du bonheur.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/123-bagues-pierres-naturelles', 'Bagues en pierres naturelles', 123, 34, 350, 'Chaque bague en pierre naturelle La Maison de l’Ambre raconte une histoire, celle de la terre et de ses trésors minéraux. Façonnée autour d’une pierre choisie avec soin pour sa couleur, son éclat et son énergie, nos créations sont des bijoux uniques. Entre symbolique et authenticité, trouvez la bague qui vous ressemble.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/124-bijoux-agate', 'Bijoux en agate', 124, 34, 68, 'L’agate captive par la richesse de ses nuances et par sa beauté minérale. Les bijoux en agate de La Maison de l’Ambre associent cette pierre naturelle à des métaux précieux, créant des parures lumineuses et uniques. Renvoyant à l''équilibre et à la sérénité, chacun de bijoux en agate reflètent authenticité et élégance.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/125-bijoux-amazonite', 'Bijoux en amazonite', 125, 34, 4, 'Les bijoux en amazonite de LMDLA séduisent par leur camaïeu de verts, symboles de douceur et de quiétude, mais aussi par leur design original. Optez pour l''éclat naturel et les reflets de l''amazonite ; des bijoux faciles à porter et à assortir, livrés avec un certificat en gage de leur qualité et de leur caractère unique.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/126-bijoux-ambre', 'Bijoux en ambre', 126, 34, 554, 'Les bijoux en ambre de LMDLA mettent en valeur l’éclat chaleureux et naturel de la résine de la mer Baltique. Chaque bijou de notre collection est authentique et intemporel, comme la pierre d''ambre qui le rend si unique. Nos créations en ambre illuminent vos instants de vie, livrées avec un certificat d’authenticité.', 'Découvrez notre guide de présentation sur les bijoux en ambre et comment les choisir !

 Découvrez l’éclat unique de nos bijoux en ambre , façonnés à partir d’ ambre naturel issu de la mer Baltique . Chaque article de notre collection de bijoux incarne la rencontre entre la nature et le savoir-faire artisanal de notre Maison. Depuis 1973, La Maison de l''Ambre s’attache à sublimer cette belle résine fossile sous toutes ses formes et ses couleurs : colliers, bracelets, boucles d’oreilles, bagues et pendentifs. Nos créations, à la fois intemporelles et élégantes, s’adressent aux femmes, aux hommes et aux enfants en quête d’un bijou authentique, chargé d’histoire et de lumière. Un petit morceau de nature qui nous rappelle que nous faisons partie d''un tout.

 L’origine et la beauté de l’ambre baltique

 L’ ambre de la Baltique est une matière fascinante, née il y a plusieurs millions d’années de la fossilisation d’une résine végétale naturelle. Cette pierre organique, aussi appelée « or du Nord », se distingue par sa couleur chaude et ses reflets dorés, du jaune miel au cognac, jusqu’à des nuances plus vertes ou orangées. C''est uniquement cet ambre que nous choisissons pour donner vie à nos créations uniques. Nos artisans sélectionnent avec soin chaque pièce d’ ambre naturel , en veillant à préserver son authenticité et sa transparence. Ce matériau d’exception est ensuite associé à des structures en argent design épurées, qui mettent en valeur la beauté brute de la pierre, sans jamais la dénaturer.

 Une grande variété de modèles pour tous les styles

 Nos bijoux en ambre se déclinent dans une grande variété de modèles et de formes. Les colliers en perles d''ambre ou les pendentifs gouttes habillent le cou avec raffinement. Parcourez nos modèles de bracelets qui s’ajustent parfaitement à votre poignet, grâce à leurs montures élastiques ou chaînes en argent, combinant ambre et argent.

 Les boucles d''oreilles, bagues ou broches, séduisent aussi par leurs teintes lumineuses et leurs motifs inspirés de la nature : perle, feuille, goutte ou encore arbre de vie. Vous trouverez également des pendentifs et  bijoux fantaisie au style plus contemporain, pensés pour sublimer vos tenues quotidiennes ou lors des occasions plus spéciales. L''ambre n''a ni âge ni sexe et peut parfaitement sublimer toutes les tenues, des plus classiques aux plus raffinées.

 Pour les plus petits, nos bijoux ambre bébé sont conçus avec le plus grand soin : chaque article est certifié, livré dans son écrin et conforme aux normes de sécurité en vigueur.

 Chaque  bijou en ambre que nous proposons est issu d’une fabrication maîtrisée, alliant authenticité, qualité et innovation. Nos créations respectent les normes REACH, garantissant l’absence de substances nocives. Tous nos métaux sont hypoallergéniques et inoxydables, afin que vous puissiez porter votre bijou au quotidien sans altération ni irritation.

 Chez La Maison de l''Ambre, nous travaillons exclusivement avec des matériaux nobles : ambre et argent  mais aussi avec des perles ou des pierres complémentaires hautes en couleurs et en reflet. Chaque bijou, fourni avec son certificat, bénéficie d’une garantie de deux ans, d’une livraison rapide et soignée, et d’un paiement sécurisé. Vous profitez également de la livraison gratuite à l’international selon le montant de votre achat.

 Symbolique et vertus de l’ambre

 L’ambre fascine depuis toujours par ses vertus et son pouvoir symbolique. En lithothérapie, il serait réputé pour diffuser une énergie chaleureuse et bienfaisante. Sa richesse en acide succinique lui conférerait des propriétés apaisantes, capables de calmer les tensions ou de rendre moins douloureuses les poussées dentaires des bébés. Les bijoux en ambre sont alors de très jolis cadeaux de naissance ou présents à offrir au premier anniversaire d''un jeune enfant.

 Bien que ces bienfaits ne soient pas scientifiquement prouvés, beaucoup considèrent l’ambre comme une pierre de la sérénité, associée à la lumière et à la vitalité. Porter un bijou en ambre , c’est aussi renouer avec un fragment de nature millénaire.

 Porter un bijou en ambre , c’est choisir la qualité, la lumière et la nature. Chaque création témoigne du savoir-faire de notre bijouterie et de l’amour des pierres naturelles. Explorez dès maintenant notre collection de bijoux en ambre naturel , et laissez-vous séduire par leur charme solaire et intemporel.

 Où acheter des bijoux en ambre ?

 Nos créations sont mises en vente directement sur les pages de notre bijouterie en ligne LMDLA . Vous y trouverez l’ensemble de notre collection de bijoux en ambre, classée par meilleur vente, nouveauté ou prix, avec la possibilité de filtrer les résultats selon vos envies. Suivez la tendance ou cherchez la pépite précieuse que tout le monde vous enviera.

 Quels sont les prix des bijoux en ambre ?

 Nos modèles s’adaptent à tous les budgets, du fin bracelet à la bague pour femme plus travaillée. Chez LMDLA, les tarifs varient selon la taille de la pierre d'' ambre naturel et celle du bijou qui la met en valeur. Du pendentif design à la bague plus traditionnelle, vous êtes sûr de bénéficier d’un excellent rapport qualité-prix.

 Comment nettoyer les bijoux en ambre ?

 Pour préserver l’éclat et l''authenticité de vos bijoux, nettoyez-les simplement avec un chiffon doux, un peu d’eau savonneuse. Si besoin, pour redonner plus d''éclat à l''argent, vous pouvez ajouter une touche de citron très diluée. Évitez tout produit chimique ou abrasif, afin de conserver la surface lisse et brillante de la résine.

 Comment choisir un bijou en ambre ?

 Sélectionnez votre bijou selon votre style, la matière, la couleur qui vous attire le plus (miel, cognac, vert ou orange) et l’usage que vous souhaitez en faire : cadeau d’anniversaire, bijou de fête ou simple petit cadeau plaisir pour soi-même. Chaque création est unique, comme la personne qui la portera. Dans nos catégories, vous aurez la possibilité de trier et de filtrer à votre convenance par le type de matière, le type de bijoux, etc... Vous pouvez également choisir des bijoux en ambre avec des pierres secondaires comme du lapiz-lazuli, de la citrine et bien d''autres pierres précieuses, selon vos préférences.

 Quelle est l’origine de l’ambre ?

 L’ambre provient principalement des pays baltes , à partir de la résine des forêts préhistoriques de ces régions du nord-est de l''Europe. Cette histoire naturelle fascinante en fait bien plus qu’un simple bijou fantaisie : un fragment d’éternité, un éclat de lumière et de vie subtilement capturé.', null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/127-bijoux-amethyste', 'Bijoux en améthyste', 127, 34, 96, 'Les bijoux en améthyste LMDLA, avec leur violet profond, presque secret, sont des trésors naturels à la portée de tous. Nous vous dévoilons des bijoux élégants et durables, dont nous connaissons la traçabilité. Nos bijoux en améthyste apportent une touche de couleur et de douceur à toutes vos tenues, qu''ils soient pour vous ou pour offrir.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/128-bijoux-argent-pierres-naturelles', 'Bijoux en argent et pierres naturelles', 128, 34, 1061, 'Les bijoux en argent et pierres naturelles sont toujours une histoire de rencontre ! Celle de la pureté du métal et de la richesse minérale, marquant tous vos instants de vie. LMDLA vous présente des créations en argent 925 certifiées et pierres naturelles minutieusement contrôlées. Des bijoux qui unissent puissance de la nature et élégance.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/129-bijoux-aventurine', 'Bijoux en aventurine', 129, 34, 29, 'Nos bijoux en aventurine mettent en lumière la beauté unique de cette pierre naturelle au nom poétique. Symbole de fraîcheur et de vitalité, l''aventurine et ses tons verts très doux sont faciles à porter et à assortir. Offrez un bijou en aventurine, alliance parfaite entre authenticité et raffinement, toujours livré avec sa preuve d''authenticité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/130-bijoux-calcedoine', 'Bijoux en calcédoine', 130, 34, 18, 'La calcédoine séduit par la douceur de son bleu et ses nuances lumineuses. Trouvez les bijoux en calcédoine que vous recherchez, pièces délicates et accessibles, parmi les collections de La Maison de l''Ambre. Nous vous proposons des parures élégantes et des bijoux authentiques, pour dire vos sentiments ou simplement pour vous faire plaisir.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/131-bijoux-dore-pierres-naturelles', 'Bijoux doré et pierres naturelles', 131, 34, 56, 'Voici des bijoux dorés et pierres naturelles pour sublimer tous les instants. La brillance de l''argent doré et la puissance minérale s’unissent dans ces créations signées LMDLA. Tous nos bijoux, associant éclat moderne et beauté de la nature, sont livrés avec leur certificat d’authenticité. Une jolie manière de lier raffinement et symbolique.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/132-bijoux-grenat', 'Bijoux en grenat', 132, 34, 7, 'Les bijoux en grenat LMDLA reflètent l’intensité de cette pierre de feu, trésor minéral aux nuances rouges envoûtantes. Porter un bijou en grenat, c’est s’offrir une touche d’énergie et de passion, chargée d’authenticité et de beauté. Élégants et intemporels, nos bijoux en grenat subliment vos tenues et révèlent votre personnalité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/133-bijoux-jaspe', 'Bijoux en jaspe', 133, 34, 6, 'Retrouvez parmi nos bijoux en jaspe celui qui raconte votre histoire, avec ses nuances minérales uniques. Sélectionnée pour ses couleurs profondes et son énergie singulière, chaque pierre fait des créations LMDLA un bijou authentique. Porter un bijou en jaspe à l''origine certifiée, c’est s’offrir un fragment de nature, symbole de force et d’élégance.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/134-bijoux-labradorite', 'Bijoux en labradorite', 134, 34, 39, 'Les bijoux en labradorite LMDLA séduisent par leurs reflets changeants, du gris profond aux éclats bleutés. Nos artisans ont su mettre en valeur cette pierre naturelle unique et authentique dans une collection de bijoux aux reflets irisés. Tous nos bijoux en labradorite sont livrés avec leur certificat d’authenticité, gage de qualité et de savoir-faire.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/135-bijoux-lapis-lazuli', 'Bijoux en lapis lazuli', 135, 34, 9, 'Le lapis lazuli, d’un bleu profond parsemé de paillettes dorées, incarne beauté et noblesse. Nos bijoux en lapis lazuli mettent en valeur cette pierre naturelle emblématique à travers des créations raffinées. Authentiques et élégants, les bijoux en lapis lazuli LMDLA se portent au quotidien ou s’offrent comme cadeaux précieux, avec leur certificat d’authenticité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/136-bijoux-lithotherapie', 'Bijoux de lithothérapie', 136, 34, 1163, 'Les bijoux de lithothérapie de LMDLA sont ornés de pierres naturelles, réputées pour leurs potentiels bienfaits. Chaque création unit beauté et symbolique, transformant l’énergie minérale en bijou, pour votre plus grand plaisir. Portés au quotidien, ils invitent à l’équilibre et accompagnent vos plus beaux instants de vie, tout en élégance.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/137-bijoux-multipierres', 'Bijoux multipierres', 137, 34, 23, 'Les bijoux multipierres célèbrent la diversité de la nature et la richesse minérale. Chaque création La Maison de l’Ambre unit plusieurs pierres naturelles, choisies pour leurs couleurs, leur pureté et leur symbolique. Trouvez le bijou unique multipierres qui reflètera votre personnalité, facile à porter au quotidien comme lors de grandes occasions.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/138-bijoux-nacre', 'Bijoux en nacre', 138, 34, 7, 'Les bijoux en nacre sont comme de petits reflets de l''océan, à la fois délicats et puissants. C''est une célèbre matière minérale, fascinant par ses éclats irisés, sublimée ici par le design unique de nos créations. Laissez les bijoux en nacre LMDLA, et leurs potentiels bienfaits apaisants, faire toute la lumière sur votre style.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/139-bijoux-onyx', 'Bijoux en onyx', 139, 34, 15, 'L’onyx, pierre noire et profonde, incarne sobriété et intensité. Les bijoux en onyx de La Maison de l’Ambre associent le métal précieux à cette pierre naturelle élégante, pour des bijoux authentiques et hors du commun. Trouvez le bijou en onyx capable de souligner votre style, livré avec un certificat d''authenticité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/140-bijoux-opale', 'Bijoux en opale', 140, 34, 89, 'Offrez des bijoux en opale pour plaire et fasciner à la fois. Cette pierre précieuse aux reflets changeants donne à chacun des bijoux LMDLA un caractère singulier. Souvent liés à la créativité et à l’intuition, nos bijoux en opale sont des vecteurs de poésie et de lumière, toujours livrés avec un certificat prouvant leur authenticité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/141-bijoux-pierre-lune', 'Bijoux en pierre de lune', 141, 34, 39, 'Nos bijoux en pierre de lune se parent de reflets subtils et poétiques, pour les petits et les grands rêveurs. La Maison de l''Ambre vous dévoile des bijoux certifiés, ornés de pierres de lune 100 % naturelles. Associée à l''intuition et à l''harmonie, cette pierre propose une variété de couleurs, pour convenir à tous les styles.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/142-bijoux-prehnite', 'Bijoux en préhnite', 142, 34, 7, 'La préhnite, aux tons verts et doux, symbolise fraîcheur et apaisement. Découvrez les bijoux en préhnite de LMDLA, révélant le charme naturel et la douceur subtile de cette pierre rare. Nous contrôlons et certifions l''origine de toutes nos créations, pour vous garantir des cadeaux durables et raffinés qui plairont à coup sûr.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/143-bijoux-quartz', 'Bijoux en quartz', 143, 34, 100, 'Cristallins et lumineux, les bijoux en quartz incarnent pureté et clarté. LMDLA présente plusieurs types de bijoux en quartz certifiés, au design original, soulignant la puissance et la beauté de cette pierre naturelle universelle. Réputé pour ses potentiels bienfaits énergétiques, le quartz est une pierre qui vous permet de miser sur l''intemporel et le raffinement.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/144-bijoux-shattuckite', 'Bijoux en shattuckite', 144, 34, 12, 'Cap sur la profondeur des océans et leurs nuances de bleu intenses avec nos bijoux en shattuckite. C''est l''une des pierres choisies par LMDLA pour sa pureté et ses reflets. Nos créations en shattuckite se marient avec tous les styles, intemporelles et saisissantes. Quel bijou associé à l''intuition et à la communication choisirez-vous ?', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/145-bijoux-silex', 'Bijoux en silex', 145, 34, 8, 'Laissez nos bijoux en silex vous séduire, par leur caractère brut, minéral et leur design élégant. Symbole de force ancestrale, le silex fascine depuis des siècles, et c''est pour cela que les ateliers LMDLA avaient envie de le sublimer. Ancrage et protection, robustesse et puissance, il y a mille raisons de craquer pour un bijou en silex.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/146-bijoux-topaze', 'Bijoux en topaze', 146, 34, 3, 'Les bijoux en topaze LMDLA dévoilent toute la lumière et la délicatesse de cette pierre naturelle aux nombreux reflets. Du bleu clair au doré éclatant, la topaze incarne élégance et raffinement sous de multiples facettes. Chaque création magnifie vos tenues, révélant la beauté de cette gemme intemporelle et celle de la personne qui la porte.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/147-bijoux-turquoise', 'Bijoux en turquoise', 147, 34, 20, 'D’un bleu vibrant, nos bijoux en turquoise sont ornés de cette pierre emblématique à la beauté solaire. Synonyme d''évasion, liée à la protection et à l''harmonie, la turquoise permet aux créations LMDLA d''associer éclat minéral et élégance du métal, pour des bijoux hors du temps : cadeaux simples et exceptionnels à la fois.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/148-boucles-oreilles-pierres-naturelles', 'Boucles d''oreilles en pierres naturelles', 148, 34, 267, 'Mariez éclat minéral et élégance avec nos boucles d’oreilles en pierres naturelles. Chacune des paires de boucles d''oreilles LMDLA se pare de pierres naturelles authentiques dont nous avons contrôlé l''origine. Optez pour l''harmonie, l''équilibre et la beauté de la nature avec nos différentes créations ; des bijoux colorés, symboliques et durables.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/149-bracelets-pierres-naturelles', 'Bracelets en pierres naturelles', 149, 34, 145, 'Nos bracelets en pierres naturelles célèbrent la beauté de la Terre. Découvrez la collection des bracelets uniques LMDLA, décorés de pierres naturelles véritables, minutieusement sélectionnés, pour vous offrir vitalité et bien-être. Que vous soyez sensible ou pas aux potentiels bienfaits des pierres, votre bracelet apportera authenticité et éclat naturel à votre poignet.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/150-colliers-pierres-naturelles', 'Colliers en pierres naturelles', 150, 34, 233, 'Les colliers en pierres naturelles de LMDLA vous permettent de célébrer la beauté brute de la nature, et de faire plaisir à vos proches. Chaque pierre, choisie pour sa singularité, ses couleurs et ses reflets, devient le maillon d''une création singulière. Des créations uniques pour mettre en valeur ceux qui les portent, entre élégance et symbolique.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/151-pendentifs-pierres-naturelles', 'Pendentifs en pierres naturelles', 151, 34, 167, 'Exprimez votre personnalité avec nos pendentifs en pierres naturelles. Chaque création associe la force d''un métal précieux à la beauté minérale d''une ou de plusieurs pierres à l''origine certifiée, choisies avec soin par nos équipes. Chaleur, équilibre, bien-être, nos pendentifs sont comme des talismans symboliques, à porter ou à offrir.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/153-bracelets-bebe', 'Bracelets pour bébé', 153, 111, 5, 'Délicats et sûrs, les bracelets pour bébé de La Maison de l’Ambre sont conçus dans nos ateliers, en métal hypoallergénique et conformément aux normes européennes. Cadeaux de naissance ou de baptême, ils incarnent les souvenirs précieux que l’on conserve toute une vie. Des bijoux symboliques, pensés pour accompagner les premiers instants de chaque enfant.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/154-colliers-bebe', 'Colliers pour bébé', 154, 111, 10, 'Les colliers pour bébé sont des cadeaux symboliques, porteurs de sens et de sentiments. LMDLA sait combien la célébration des premiers instants de vie est importante et vous propose des colliers pour bébé hypoallergéniques et conformes aux normes européennes. Naissance, baptême ou anniversaire, offrez un petit peu de tendresse et d''originalité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/170-bijoux-agate-blue-lace', 'Bijoux en agate blue lace', 170, 124, 12, 'Laissez nos bijoux en agate blue lace vous conter leur histoire, associés à l''harmonie intérieure, à la positivité et à l''apaisement. LMDLA associe la puissance naturelle de cette pierre aux teintes bleu ciel et le savoir-faire de sa Maison pour vous dévoiler des créations singulières. Choisissez votre bijou en agate blue lace comme un précieux cadeau.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/171-bagues-agate', 'Bagues en agate', 171, 124, 16, 'Parmi les créations LMDLA figurent les bagues en agate, symbole de la beauté minérale et des mille nuances de la Terre. Chaque pierre, aux nuances uniques allant du gris bleuté aux teintes plus chaleureuses, fait de nos bagues en agate des créations singulières. Faites le choix de l''authenticité avec ce bijou aux nombreux bienfaits potentiels.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/172-bracelets-agate', 'Bracelets en agate', 172, 124, 7, 'Laissez-vous séduire par l’un de nos bracelets en agate, pierre aux nuances infinies, tantôt douces, tantôt profondes. Chaque bracelet LMDLA devient un jeu de couleurs minérales qui illumine le poignet et révèle votre élégance naturelle. Optez pour les potentiels bienfaits calmants de l''agate, pour affirmer un style unique, authentique et pourtant, résolument moderne.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/173-colliers-agate', 'Colliers en agate', 173, 124, 7, 'Nos colliers en agate sont des accessoires parfaits pour ajouter une pointe de caractère à vos tenues. Chaque agate révèle des dessins naturels uniques et devient dans les ateliers LMDLA, le cœur de bijoux singuliers. Livrés avec leur certificat d’authenticité, nos colliers en agate sont des symboles d''équilibre et de sérénité pour tous.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/174-boucles-oreilles-agate', 'Boucles d''oreilles en agate', 174, 124, 22, 'Optez pour la douceur intemporelle et la brillance avec nos boucles d’oreilles en agate. Une petite pierre précieuse qui a tout d''une grande, avec une éblouissante palette de reflets. La Maison de l’Ambre vous présente des boucles d’oreilles en agate certifiées, aux nuances minérales uniques, symbole d’équilibre et de sérénité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/175-pendentifs-agate', 'Pendentifs en agate', 175, 124, 16, 'Les pendentifs en agate LMDLA sont comme des amulettes précieuses, où chaque pierre devient œuvre unique de la nature. Son éventail de nuances, sombres et profondes ou plus délicates, capte la lumière pour vous raconter une histoire unique. Bijoux intemporels, certifiés et élégants, nos pendentifs en agate deviennent des trésors à porter près du cœur.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/158-bijoux-ambre-argent', 'Bijoux en ambre et argent', 158, 126, 497, 'Spécialité de notre maison depuis 1973, les bijoux en ambre et argent LMDLA sont le reflet de nos valeurs : authenticité, qualité et tradition. L’ambre de la mer Baltique dévoile son éclat chaleureux, sublimé par la pureté du métal précieux. Chaque création en argent 925 est livrée avec son certificat d’authenticité, preuve d''un savoir-faire maîtrisé.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/159-bijoux-ambre-dore', 'Bijoux en ambre et doré', 159, 126, 11, 'Au croisement de la tradition et de la modernité, LMDLA vous présente ses bijoux en ambre et argent doré. L’ambre de la mer Baltique, que nous chérissons depuis 1973, produit des joyaux naturels, sublimés par nos bijoux aux reflets d''or. Nos créations emblématiques, en argent doré 925 et ambre, sont livrées avec un certificat d’authenticité.', null, null, null, null, null, null),
('dd5cc453-308b-4b24-822d-ef70e77b4438'::uuid, 'https://lamaisondelambre.com/fr/160-bijoux-ambre-enfant', 'Bijoux en ambre pour enfant', 160, 126, 15, 'À la recherche de bijoux en ambre pour enfant empreints de douceur et de naturel ? LMDLA vous dévoile sa collection de créations hypoallergéniques en métal précieux, ornées d’ambre de la mer Baltique à l’origine certifiée. De petits trésors lumineux, pensés pour accompagner l’enfant dans ses étapes de vie : naissance, baptême, anniversaire ou souvenir précieux.', null, null, null, null, null, null)
on conflict (project_id, url) do update set
  name = excluded.name, external_id = excluded.external_id,
  parent_external_id = excluded.parent_external_id,
  products_count = excluded.products_count,
  catalog_short_description = excluded.catalog_short_description,
  catalog_long_description = excluded.catalog_long_description,
  target_keyword = coalesce(excluded.target_keyword, public.categories.target_keyword),
  keyword_volume = coalesce(excluded.keyword_volume, public.categories.keyword_volume),
  keyword_difficulty = coalesce(excluded.keyword_difficulty, public.categories.keyword_difficulty),
  keyword_intent = coalesce(excluded.keyword_intent, public.categories.keyword_intent),
  keyword_data_at = coalesce(excluded.keyword_data_at, public.categories.keyword_data_at),
  updated_at = now();
